export const theme = {
  colors: {
    black: "#131717",
    white: "#fff",
    lightGray: "#9B9E9F",
    primary: {
      dark: "#097420",
      normal: "#2DC44D",
      light: "#A7E0C0",
      lighter: "#E5F6ED",
      hover: "#2DA64D",
    },
    secondary: {
      dark: "#004787",
      normal: "#0087ff",
      light: "#66B7FF",
      lighter: "#E5F3FF",
      hover: "#0070D3",
    },
    darkBlue: {
      dark: "#021141",
      normal: "#1b2f6f",
      light: "#5F6D9A",
      lighter: "#E8EAF0",
    },
    red: {
      dark: "#B20006",
      normal: "#ff3b42",
      light: "#FF757A",
      lighter: "#FFEBEC",
    },
    purple: {
      dark: "#4F1BB7",
      normal: "#9966FF",
      light: "#B793FF",
      lighter: "#F4EFFF",
    },
    sky: {
      dark: "#A2ACAB",
      normal: "#C2CAC8",
      light: "#D7DDDB",
      lighter: "#EFF3F2",
      extraLight: "#F8FAF9",
      extraLighter: "#FBFBFB",
    },
    enlaci: {
      dark: "#021141",
      normal: "#1B2F6F",
      light: "#5F6D9A",
      lighter: "#E8EAF0",
    },
    enred: {
      dark: "#B20006",
      normal: "#FF3B42",
      light: "#FF757A",
      lighter: "#FFEBEC",
    },
    enpurple: {
      dark: "#4F1BB7",
      normal: "#9966FF",
      light: "#B793FF",
      lighter: "#F4EFFF",
    },
    text: {
      darkest: "#222827",
      dark: "#131717",
      normal: "#727E7C",
      light: "#939D9A",
      lighter: "#BDC5C1",
    },
    warning: "#EAA61A",
    error: "#E12424",
    info: "#2D7FC4",
    success: "#6AC42D",
    gray: "#D7DDDB",
    mediumlight: "unknown",
  },
  fontSizes: {
    xs: "12px",
    sm: "14px",
    md: "16px",
    lg: "18px",
    xl: "20px",
    xxl: "24px",
  },
  fontWeights: {
    normal: 400,
    bold: 600,
    bolder: 700,
  },
  fontFamilies: {
    primary: "Open Sans, sans-serif",
  },
  lineHeights: {
    xs: "16px",
    sm: "18px",
    md: "20px",
    lg: "22px",
    xl: "24px",
    xxl: "28px",
  },
  letterSpacings: {
    xs: "0.5px",
    sm: "0.5px",
    md: "0.5px",
    lg: "0.5px",
    xl: "0.5px",
    xxl: "0.5px",
  },
  spaces: {
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "20px",
    xxl: "24px",
  },
  borderRadius: {
    xs: "2px",
    sm: "4px",
    md: "6px",
    lg: "8px",
    xl: "10px",
    xxl: "12px",
  },
};
